<a href="https://colab.research.google.com/github/y2om/Colab/blob/main/3%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3일차

클래스
* 객체지향 : 객체 간의 상호작용으로서 시스템의 행동을 파악하는 사고방식
클래스 : 설계도
인스턴스 : 설계도로 만들어진 제품

클래스 :class로 사용하여 클래스에는 여러 개의 메소드가 포함됨
메소드는 함수와 비슷하며, def로 기술을 시작
파이썬의 메소드에서는 첫 번째 인수로서 self를 받는 특징이 있다. self를 이용해 이른바 인스턴스 변수에 접근 가능 인스턴스 변수는 클래스로부터 생성한 인스턴스가 보유하는 변수
__init__()는 특수한 메소드로 이니셜라이저 혹은 생성자라고 함 . 이것으 인스턴스 생성 시에 인스턴스의 초기 설정을 할 수 있다. 상기의 클래스에서는 self.a=a로 인수로서 받은 값을 인스턴스 변수a에 대입한다.
add()메소드와 multiply()메소드에서는 인수로 받은 값과 인스턴스 변수a와의 사이에서 연산하고 있다.

클래스에는 상속이라는 개념이 있음 클래스를 상속함으로써 기존의 클래스를 상속받은 후에 새로운 클래스를 정의 가능

__call__() 메소드를 사용하면 메소드 명을 기술할 필요가 없어진다. 빈번히 이용하는 처리를 메소드에 기술하는 것으로 코드의 기술이 줄어든다.

with구문 : 파일 읽기 및 저장을 간결하게 기술할 수 있다.

Numpy: 딥러닝 코드에서 빈번히 사용하는 파이썬 확장 모듈
import numpy as np->이렇게 코드의 맨앞에 기술해 사용 가능
배열 : 인공지능, 딥러닝 계산에는 여러 개의 수치를 사용하는데, 이러한 수치를 저장하기 위해서 numpy 배열을 자주 사용

shape(): 배열의 형태를 얻음
reshape() : 배열의 형태를 변환->reshape(-1)과 같이 인수에 -1을 건넴으로써 어떤 배열이라도 1차원 배열으로 변환 가능
sum : 합계
average : 평균
min : 최솟값
max : 최댓값
axis를 지정하면 특정 방향으로 연산 가능 ex. axis=0-> 세로, axis=1-> 가로

In [2]:
class Calc :
  def __init__(self,a):
    self.a=a

  def add(self,b):
    print(self.a+b)

  def multiply(self,b):
    print(self.a*b)


In [3]:
calc=Calc(4)  #초기값을 4로 지정
calc.add(5)   #초기값에 5를 더함
calc.multiply(4)  #4x4

9
16


In [5]:
class CalcNext(Calc):
  def subtract(self,b):
    print(self.a-b)
  def divide(self,b):
    print(self.a/b)

In [6]:
calc_next=CalcNext(4)
calc_next.add(5)
calc_next.multiply(5)
calc_next.subtract(5)
calc_next.divide(5)

9
20
-1
0.8


In [10]:
class Calc:
  def __init__(self,a):
    self.a=a

  def __call__(self,c):
    print(self.a*c+c)

  def add(self,b):
    print(self.a+b)

  def multiply(self,b):
    print(self.a+b)

In [11]:
cl=Calc(3)
cl(5)

20


In [16]:
greetings='Good morning!\nGood afternoon!\nGood evening!\nGood night!'
with open('greetings.txt','w') as f:
  f.write(greetings)

In [17]:
with open('greetings.txt','r')as f:
  print(f.read())


Good morning!
Good afternoon!
Good evening!
Good night!


In [18]:
import numpy as np
a=np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [19]:
import numpy as np
b=np.array([[0,1,2],[3,4,5]])
print(b)  #2차원 배열

[[0 1 2]
 [3 4 5]]


In [21]:
import numpy as np
c=np.array([[[0,1,2,],[1,2,3]],[[2,3,4],[3,4,5]]])
print(c)

[[[0 1 2]
  [1 2 3]]

 [[2 3 4]
  [3 4 5]]]


In [24]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(a)
print() #빈칸 만들려고 출력
print(a+2)
print()
print(a*2)

[[0 1 2]
 [3 4 5]]

[[2 3 4]
 [5 6 7]]

[[ 0  2  4]
 [ 6  8 10]]


In [25]:
b=np.array([[0,1,2],[3,4,5]])
c=np.array([[1,2,3],[4,5,6]])
print(b)
print()
print(c)
print()
print(b+c)
print()
print(b*c)

[[0 1 2]
 [3 4 5]]

[[1 2 3]
 [4 5 6]]

[[ 1  3  5]
 [ 7  9 11]]

[[ 0  2  6]
 [12 20 30]]


In [26]:
d=np.array([[1,1],[1,1]])
e=np.array([1,2])
print(d)
print()
print(e)
print()
print(d+e)

[[1 1]
 [1 1]]

[1 2]

[[2 3]
 [2 3]]


In [27]:
import numpy as np
a= np.array([[0,1,2],[3,4,5]])
print(a.shape)    #2행 3열

(2, 3)


In [28]:
b=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
c=b.reshape(3,4)

print(b)
print()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
import numpy as np
a=np.array([0,1,2,3,4,5])
print(a[3])

3


In [30]:
import numpy as np
a=np.array([0,1,2,3,4,5])
a[3]=99
print(a)

[ 0  1  2 99  4  5]


In [32]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(a[1,0])

3


In [35]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
a[1,2]=99
print(a)

[[ 0  1  2]
 [ 3  4 99]]


In [37]:
import numpy as np
def a_func(x):
  y=x*2+1
  return y
a=np.array([[0,1,2],[3,4,5]])
b=a_func(a)
print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[ 1  3  5]
 [ 7  9 11]]


In [39]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.average(a))
print(np.min(a))
print(np.max(a))

21
3.5
1
6


In [40]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(np.average(a,axis=0))
print(np.average(a,axis=1))

[2.5 3.5 4.5]
[2. 5.]
