<a href="https://colab.research.google.com/github/y2om/Colab/blob/main/%EA%B5%AC%EA%B8%80%20%EC%BD%94%EB%9E%A9%EC%9C%BC%EB%A1%9C%20%EB%B0%B0%EC%9A%B0%EB%8A%94%20%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EA%B8%B0%EC%88%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
class Calc :
  def __init__(self,a):
    self.a=a

  def add(self,b):
    print(self.a+b)

  def multiply(self,b):
    print(self.a*b)


In [3]:
calc=Calc(4)  #초기값을 4로 지정
calc.add(5)   #초기값에 5를 더함
calc.multiply(4)  #4x4

9
16


In [5]:
class CalcNext(Calc):
  def subtract(self,b):
    print(self.a-b)
  def divide(self,b):
    print(self.a/b)

In [6]:
calc_next=CalcNext(4)
calc_next.add(5)
calc_next.multiply(5)
calc_next.subtract(5)
calc_next.divide(5)

9
20
-1
0.8


In [10]:
class Calc:
  def __init__(self,a):
    self.a=a

  def __call__(self,c):
    print(self.a*c+c)

  def add(self,b):
    print(self.a+b)

  def multiply(self,b):
    print(self.a+b)

In [11]:
cl=Calc(3)
cl(5)

20


In [16]:
greetings='Good morning!\nGood afternoon!\nGood evening!\nGood night!'
with open('greetings.txt','w') as f:
  f.write(greetings)

In [17]:
with open('greetings.txt','r')as f:
  print(f.read())


Good morning!
Good afternoon!
Good evening!
Good night!


In [18]:
import numpy as np
a=np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [19]:
import numpy as np
b=np.array([[0,1,2],[3,4,5]])
print(b)  #2차원 배열

[[0 1 2]
 [3 4 5]]


In [21]:
import numpy as np
c=np.array([[[0,1,2,],[1,2,3]],[[2,3,4],[3,4,5]]])
print(c)

[[[0 1 2]
  [1 2 3]]

 [[2 3 4]
  [3 4 5]]]


In [24]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(a)
print() #빈칸 만들려고 출력
print(a+2)
print()
print(a*2)

[[0 1 2]
 [3 4 5]]

[[2 3 4]
 [5 6 7]]

[[ 0  2  4]
 [ 6  8 10]]


In [25]:
b=np.array([[0,1,2],[3,4,5]])
c=np.array([[1,2,3],[4,5,6]])
print(b)
print()
print(c)
print()
print(b+c)
print()
print(b*c)

[[0 1 2]
 [3 4 5]]

[[1 2 3]
 [4 5 6]]

[[ 1  3  5]
 [ 7  9 11]]

[[ 0  2  6]
 [12 20 30]]


In [26]:
d=np.array([[1,1],[1,1]])
e=np.array([1,2])
print(d)
print()
print(e)
print()
print(d+e)

[[1 1]
 [1 1]]

[1 2]

[[2 3]
 [2 3]]


In [27]:
import numpy as np
a= np.array([[0,1,2],[3,4,5]])
print(a.shape)    #2행 3열

(2, 3)


In [28]:
b=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
c=b.reshape(3,4)

print(b)
print()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
import numpy as np
a=np.array([0,1,2,3,4,5])
print(a[3])

3


In [30]:
import numpy as np
a=np.array([0,1,2,3,4,5])
a[3]=99
print(a)

[ 0  1  2 99  4  5]


In [32]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(a[1,0])

3


In [35]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
a[1,2]=99
print(a)

[[ 0  1  2]
 [ 3  4 99]]


In [37]:
import numpy as np
def a_func(x):
  y=x*2+1
  return y
a=np.array([[0,1,2],[3,4,5]])
b=a_func(a)
print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[ 1  3  5]
 [ 7  9 11]]


In [39]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.average(a))
print(np.min(a))
print(np.max(a))

21
3.5
1
6


In [40]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(np.average(a,axis=0))
print(np.average(a,axis=1))

[2.5 3.5 4.5]
[2. 5.]
